### ISSUE TITLE
I cannot build as described in read.me

### ISSUE THREAD

**Issue by fukamike** [GMAP/DSPBench#1]
I tried to build this benchmark, but I get the following error.

mvn clean install package -P storm

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[WARNING] 'parent.relativePath' of POM com.streamer:streamer-api:1.1 (/usr/local/DSP/DSPBench/dspbench-api/pom.xml) points at com.dspbench:dspbench instead of com.streamer:streamer, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.streamer:streamer-api:1.1: Failure to find com.streamer:streamer:pom:1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[WARNING] 'parent.relativePath' of POM com.streamer:streamer-storm:1.1 (/usr/local/DSP/DSPBench/dspbench-storm/pom.xml) points at com.dspbench:dspbench instead of com.streamer:streamer, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.streamer:streamer-storm:1.1: Failure to find com.streamer:streamer:pom:1.1 in http://clojars.org/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[WARNING] 'parent.relativePath' of POM com.streamer:streamer-storm:1.1 (/usr/local/DSP/DSPBench/dspbench-spark/pom.xml) points at com.dspbench:dspbench instead of com.streamer:streamer, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.streamer:streamer-storm:1.1: Failure to find com.streamer:streamer:pom:1.1 in http://clojars.org/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[WARNING] 'parent.relativePath' of POM com.streamer:streamer-storm:1.1 (/usr/local/DSP/DSPBench/dspbench-flink/pom.xml) points at com.dspbench:dspbench instead of com.streamer:streamer, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.streamer:streamer-storm:1.1: Failure to find com.streamer:streamer:pom:1.1 in http://clojars.org/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[WARNING] 'parent.relativePath' of POM com.streamer:streamer-local:1.1 (/usr/local/DSP/DSPBench/dspbench-local/pom.xml) points at com.dspbench:dspbench instead of com.streamer:streamer, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.streamer:streamer-local:1.1: Failure to find com.streamer:streamer:pom:1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[WARNING] 'parent.relativePath' of POM com.streamer:streamer-examples:1.1 (/usr/local/DSP/DSPBench/dspbench-applications/pom.xml) points at com.dspbench:dspbench instead of com.streamer:streamer, please verify your project structure @ line 6, column 13
[FATAL] Non-resolvable parent POM for com.streamer:streamer-examples:1.1: Failure to find com.streamer:streamer:pom:1.1 in https://repo.osgeo.org/repository/release/ was cached in the local repository, resolution will not be reattempted until the update interval of osgeo has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 13
[ERROR] 'profiles.profile.id' must be unique but found duplicate profile with id storm @ line 110, column 17
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 261, column 21
 @
[ERROR] The build could not read 7 projects -> [Help 1]
[ERROR]
[ERROR]   The project com.streamer:streamer-api:1.1 (/usr/local/DSP/DSPBench/dspbench-api/pom.xml) has 2 errors
[ERROR]     'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[ERROR]     Non-resolvable parent POM for com.streamer:streamer-api:1.1: Failure to find com.streamer:streamer:pom:1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project com.streamer:streamer-storm:1.1 (/usr/local/DSP/DSPBench/dspbench-storm/pom.xml) has 2 errors
[ERROR]     'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[ERROR]     Non-resolvable parent POM for com.streamer:streamer-storm:1.1: Failure to find com.streamer:streamer:pom:1.1 in http://clojars.org/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project com.streamer:streamer-storm:1.1 (/usr/local/DSP/DSPBench/dspbench-spark/pom.xml) has 2 errors
[ERROR]     'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[ERROR]     Non-resolvable parent POM for com.streamer:streamer-storm:1.1: Failure to find com.streamer:streamer:pom:1.1 in http://clojars.org/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project com.streamer:streamer-storm:1.1 (/usr/local/DSP/DSPBench/dspbench-flink/pom.xml) has 2 errors
[ERROR]     'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[ERROR]     Non-resolvable parent POM for com.streamer:streamer-storm:1.1: Failure to find com.streamer:streamer:pom:1.1 in http://clojars.org/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project com.streamer:streamer-local:1.1 (/usr/local/DSP/DSPBench/dspbench-local/pom.xml) has 2 errors
[ERROR]     'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[ERROR]     Non-resolvable parent POM for com.streamer:streamer-local:1.1: Failure to find com.streamer:streamer:pom:1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project com.streamer:streamer-examples:1.1 (/usr/local/DSP/DSPBench/dspbench-applications/pom.xml) has 2 errors
[ERROR]     'profiles.profile.id' must be unique but found duplicate profile with id storm @ com.dspbench:dspbench:1.1, /usr/local/DSP/DSPBench/pom.xml, line 110, column 17
[ERROR]     Non-resolvable parent POM for com.streamer:streamer-examples:1.1: Failure to find com.streamer:streamer:pom:1.1 in https://repo.osgeo.org/repository/release/ was cached in the local repository, resolution will not be reattempted until the update interval of osgeo has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project com.dspbench:dspbench:1.1 (/usr/local/DSP/DSPBench/pom.xml) has 1 error
[ERROR]     'profiles.profile.id' must be unique but found duplicate profile with id storm @ line 110, column 17
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by mayconbordin** [comment]
I will do a refactor of the project and fix these issues. Thanks for reporting.

**Comment by mayconbordin** [comment]
The issue has been fixed. Sorry for the delay.
